services:
  jupyter:
    container_name: mario-jupyter
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: >
      jupyter lab
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --ServerApp.token=''
      --ServerApp.password=''
      --ServerApp.root_dir=/app
    ports:
      - "8888:8888"
    volumes:
      - ../src:/app/src/
      - ../data:/app/data/
